// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALYJfNUw_gAYO-_HaC4eZGkEbuW_9PuNU',
    appId: '1:113358449656:web:da4a6b1fc17c757014440d',
    messagingSenderId: '113358449656',
    projectId: 'vision-app-cd004',
    authDomain: 'vision-app-cd004.firebaseapp.com',
    storageBucket: 'vision-app-cd004.firebasestorage.app',
    measurementId: 'G-KF6WQDEM5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwXJ2qw-9T-YLjLAaxEXkISd9PCIrtSPo',
    appId: '1:113358449656:android:07463a9bcfa8622e14440d',
    messagingSenderId: '113358449656',
    projectId: 'vision-app-cd004',
    storageBucket: 'vision-app-cd004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB83KeW33bkIC6gO_31aJkMnSN4TaQU2WQ',
    appId: '1:113358449656:ios:0f65b96605a1a09a14440d',
    messagingSenderId: '113358449656',
    projectId: 'vision-app-cd004',
    storageBucket: 'vision-app-cd004.firebasestorage.app',
    iosBundleId: 'com.example.visionApp',
  );

}